package:
    name: nn
    version: 1.86.0

source:
    git_url: https://github.com/sakov/nn-c.git
    git_tag: 33cbf70dec4f64836a26dcb4a885cb09b7279dd3

build:
    number: 0
    skip: True  # [win]

requirements:
    run:
        - libgcc

test:
    commands:
        - nnbathy -V
        - conda inspect linkages -n _test nn  # [linux]

about:
    home: https://github.com/sakov/nn-c
    license: BSD-2-Clause (bundled triangle code is non-free for commercial use)
    summary: Natural Neighbours interpolation

extra:
    recipe-maintainers:
        - ocefpaf
