travis:
  secure:
    BINSTAR_TOKEN: cYxZt4x6cYuVjo6PTuId9EaZc7b6ZzmZNn4+GaGy5dxUfr9amr+zyvFrJ1nclKxCMLta/6RXwaWTwGMyB2qMWj0oeSIOT/04pDxDgyHIkQ/2qEczk3rtj7ZzQCQyDbLYdmUv3LI65pHxYbGnl17Z1KMU/9KlEQgbRmi0d/9Ntp3ZQNUhGUSrSroUIA7w7BRkQFTuiGb2Vy6Dd0Mtr8DCkVwNBwuoZ4R9e/0tiEvgXp/ki7b1x1o+02mBmaJ40UDzU4ZkPdJfWA1k8T7GEz8OEOMu59hbmLT2/+VF6BYz5gJRIuFAkqYEuWnBqyOqh0RrVmtoF2mcWA4mHzksSczeEf5LC5mknKk3QOP4Zq9a0YzNvQWkLJnwgKnlh9p/yxuFTn33GBiPom6rTiCpRUfJuEBR7Pnyf+QAHDkQxvI9caWr7l+hBb2Gb/KPMSxSOaNin2DW9W5GzMj764/9rdDUJGjvHFiQhjd9VFVMB3CBgrzmj5K0kOqbx0jl6C2bSEbtoyzRvn1XHEx97fxIEPdErBLUTRcZZQ1AszHAfpJbmrHnTjr+6Du+SHpHyUDhiKRfviHUggRTrfXj4z7AJkXbjfOsgRIkvOzWO9L0DfObWY86reQvSi9AX0yiVx+xoN5P7lTPc0oMuB1FJDmkrhUjOy5A9W055F6hyoVKkUMNZPU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
